platform :ios, '6.0'

#pod 'REMenu', '~> 1.7.1'
#pod 'MSDynamicsDrawerViewController',   '~> 1.0.2'
#pod 'PBFlatUI', '~> 1.1.0'
#pod 'AMScrollingNavbar'
#pod 'MRProgress', '~> 0.2'
#pod 'MYBlurIntroductionView', '~> 1.0.1'
#pod 'WSCoachMarksView', '~> 0.2'
#pod 'MMDrawerController', '~> 0.4.0'
#pod "PBGroupScrollController"

#pod 'JMTabView', '~> 0.0.1'
#pod 'StyledPageControl'
#pod 'DDProgressView'
#pod 'UMengSocial', '~> 3.1'
#pod 'AVOSCloudUI', '~> 2.1.2'
pod 'AVOSCloud', '~> 2.2.1'
pod 'AVOSCloudSNS', '~> 2.2.1'
pod 'AFNetworking', '~> 2.0.3'
pod 'SDWebImage', '~> 3.5.2'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.2'
pod 'iVersion', '~> 1.10.6'
#pod 'KYCircleMenu', '~> 1.1.0'
pod 'LRNavigationController',  '~> 1.0.0'
pod 'SliderViewController',  '~> 1.2.0'
#pod 'JPush', '~> 1.6.3'
pod 'OpenUDID', '~> 1.0.0'
pod 'NJKScrollFullScreen', '~> 0.2'